### ISSUE TITLE
Documentation examples don't run

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/chirps#15]
I've made a few corrections to the `get_chirps()` `@examples` section, but the S3 method for class sf point does not work and need to be fixed before resubmitting our response to the reviewers.

The object, `tp_points` is not defined but is called on line 72.

I replaced `example()` with `data()` on line 68.

**Comment by kauedesousa** [comment]
I'll check that. Also, I got another error that probably has something to do with the new version of pkg `sf`.

**Comment by kauedesousa** [comment]
I am not sure why this is not working. After many tries I decided to take away the examples using sf objects (but keep the ones in the vignette). https://github.com/agrobioinfoservices/chirps/commit/719fc18079e403df5fcbd038d5d921f9ab758e3f

**Comment by kauedesousa** [comment]
Extending the explanation on why I removed the examples. It goes fine in the R CMD checks in my machine. The earlier problem was related to one update made in the `sf` package. But I removed the examples because they break in the Travis tests, due to some missing detail in the yml setup which is quite annoying. That is the reason I decided to remove the `sf` examples.
