### ISSUE TITLE
Error: Internal server Error HTTP 500

### ISSUE THREAD

**Issue by jdnmiguel** [ropensci/chirps#40]
I have tried to download some data using the following code: 

> 
> library("chirps")
> lonlat <- data.frame(lon = c(-55.0281,-54.9857, -55.0714),  lat = c(-2.8094, -2.8756, -3.5279))
> dates <- c("2017-01-01", "2017-12-31")
> dat <- get_chirps(lonlat, dates)

which results in the following error message: 
 
> Error:  Internal server Error (HTTP 500)

I thought the problem came from my laptop, but I tried with two different and got the same issues. Do you know where it might come from?

Thank you!

**Comment by kauedesousa** [comment]
HI @jdnmiguel ,

We found an issue in the URLs for the API requests using ClimateSERV. The issue is solved now in chirps v0.1.4 https://github.com/ropensci/chirps/commit/aa094c575a0c42cc84c8bd53a28b3cfe2f3d9a20

Also when you find problems using ClimateSERV, please use the (NEW) server CHC. 

```
library("remotes")
install_github("ropensci/chirps", build_vignettes = TRUE)

library("chirps")

lonlat <- data.frame(lon = c(-55.0281,-54.9857, -55.0714),
                     lat = c(-2.8094, -2.8756, -3.5279))

dates <- c("2017-01-01", "2017-12-31")

dat <- get_chirps(lonlat, dates, server = "CHC")
````

Now you need to indicate that you want the data from ClimateSERV 

````
library("chirps")

lonlat <- data.frame(lon = c(-55.0281,-54.9857, -55.0714),
                     lat = c(-2.8094, -2.8756, -3.5279))

dates <- c("2017-01-01", "2017-12-31")

dat <- get_chirps(lonlat, dates, server = "ClimateSERV")
````

I will send this new update to CRAN soon
